version: '3'
services:
  webapp:
    restart: always
    env_file:
      - .env
    build: ./web
    ports:
      - "8000:8000"       
    depends_on:
      - postgres
  
  nginx:
    restart: always
    build: ./nginx
    ports: 
      - "80:80"
    volumes:
      - webdata:/usr/src/app/static
    depends_on:
      - webapp
  
  postgres:
    restart: always
    build: ./database
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env.db

volumes:
  dbdata:
  webdata:
